apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: angular-frontend
  ports:
    - port: 80 # Service port
      targetPort: 80 # Container port
      nodePort: 30081 # Node port (make sure it doesn't conflict with backend)

