apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
spec:
  type: NodePort
  selector:
    app: angular-frontend
  ports:
    - port: 80 # internal pod port
      targetPort: 80 # container port
      nodePort: 30080 # port on worker nodes
