name: Build & Deploy Angular Frontend Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci
        working-directory: ShoppingCart

      - name: Build Angular app
        run: ng build --configuration production
        working-directory: ShoppingCart

      - name: Run Angular app
        run: npm run build
        working-directory: ShoppingCart

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest .
        working-directory: ShoppingCart

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy Angular frontend to EC2 via Bastion
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.FRONTEND_PRIVATE_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          proxy_host: ${{ secrets.EC2_BASTION_HOST }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          proxy_port: 22

          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest

            docker stop angular-frontend || true
            docker rm angular-frontend || true

            docker run -d --name angular-frontend \
              -p 80:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest
